
import jsPDF from 'jspdf';
import { checkPageBreak } from '../pdfHeaderFooter';

export const addSummarySection = (
  doc: jsPDF,
  summary: string,
  yPosition: number,
  currentPage: number
): { yPosition: number, currentPage: number } => {
  if (!summary) {
    return { yPosition, currentPage };
  }
  
  // Always create a new page for the summary
  doc.addPage();
  currentPage++;
  yPosition = 25;
  
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Health Summary (AI Generated)', 14, yPosition);
  yPosition += 20; // Increased spacing after title
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  
  const textMargin = 14;
  const maxWidth = doc.internal.pageSize.width - (textMargin * 2);
  
  // Split summary into paragraphs for better readability
  const paragraphs = summary.split('\n\n');
  
  for (const paragraph of paragraphs) {
    const splitText = (doc as any).splitTextToSize(paragraph, maxWidth);
    doc.text(splitText, textMargin, yPosition);
    yPosition += splitText.length * 6 + 8; // Add more spacing between paragraphs
  }
  
  // Ensure there's enough space for the disclaimer
  if (yPosition > doc.internal.pageSize.height - 40) {
    doc.addPage();
    currentPage++;
    yPosition = 25;
  }
  
  // Add space before disclaimer
  yPosition += 10;
  
  // Disclaimer about AI-generated content
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text('Note: This summary was generated by an AI system and should not replace professional medical advice.', textMargin, yPosition);
  doc.text('Always consult with healthcare providers regarding health concerns and treatment decisions.', textMargin, yPosition + 5);
  
  return { yPosition: yPosition + 10, currentPage };
};
