
import jsPDF from 'jspdf';
import { checkPageBreak } from '../pdfHeaderFooter';

export const addSummarySection = (
  doc: jsPDF,
  summary: string,
  yPosition: number,
  currentPage: number
): { yPosition: number, currentPage: number } => {
  if (!summary) {
    return { yPosition, currentPage };
  }
  
  // Check if we need a page break before starting summary section
  const pageBreakResult = checkPageBreak(doc, currentPage, 100);
  yPosition = pageBreakResult.newY;
  currentPage = pageBreakResult.currentPage;
  
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('Health Summary (AI Generated)', 14, yPosition);
  yPosition += 10;
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(11);
  
  const textMargin = 14;
  const maxWidth = doc.internal.pageSize.width - (textMargin * 2);
  
  const splitText = (doc as any).splitTextToSize(summary, maxWidth);
  doc.text(splitText, textMargin, yPosition);
  
  // Disclaimer about AI-generated content
  yPosition += splitText.length * 6 + 10;
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text('Note: This summary was generated by an AI system and should not replace professional medical advice.', textMargin, yPosition);
  doc.text('Always consult with healthcare providers regarding health concerns and treatment decisions.', textMargin, yPosition + 5);
  
  return { yPosition: yPosition + 10, currentPage };
};
