
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rdtwkqwbdkyznbmdhajl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJkdHdrcXdiZGt5em5ibWRoYWpsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNDc5OTAsImV4cCI6MjA1NzYyMzk5MH0.23dQ-IEcw_c6MAw2Vym8PkKIrvAHbKvj-3zxmQ12wp4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
